apiVersion: v1
kind: Service
metadata:
  name: test-101
  # namespace omitted on purpose, see deployment.yaml.
  labels:
    app: test-101
    backstage.io/kubernetes-id: test-101
spec:
  type: NodePort
  selector:
    app: test-101
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
