apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - datasources-configmap.yaml
  - dashboard-provider-configmap.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-dashboards
    namespace: grafana
    options:
      labels:
        app: grafana
    files:
      - dashboards/cluster-pods.json
      - dashboards/service-logs.json
      - dashboards/error-explorer.json
