apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: backstage
          image: forgepath/backstage:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          command:
            - node
            - packages/backend
            - --config
            - app-config.yaml
            - --config
            - app-config.local.yaml
          env:
            - name: NODE_ENV
              value: development
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-github-token
                  key: token
            - name: BACKSTAGE_S2S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-s2s-token
                  key: token
          ports:
            - name: http
              containerPort: 7007
          readinessProbe:
            tcpSocket:
              port: 7007
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
