#!/usr/bin/env bash
# Sync platform sources (overlay files, catalog entries, scaffolder templates)
# into the scaffolded Backstage app at local/backstage/.
#
# Cheap and idempotent, runs every time you `make backstage-build` so the
# image always contains the latest platform content.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=./_env.sh
. "${REPO_ROOT}/scripts/_env.sh"

BACKSTAGE_DIR="${REPO_ROOT}/local/backstage"
OVERLAY_DIR="${REPO_ROOT}/platform/backstage/overlay"
PLATFORM_CATALOG_DIR="${REPO_ROOT}/platform/backstage/catalog"
PLATFORM_TEMPLATES_DIR="${REPO_ROOT}/platform/backstage/templates"
PLATFORM_DOCS_DIR="${REPO_ROOT}/platform/docs"

if [ ! -d "${BACKSTAGE_DIR}/packages" ]; then
  echo "local/backstage/ is not scaffolded, run \`make backstage-init\` first." >&2
  exit 1
fi

# 0. Drift check. .scaffold-pristine/ (from backstage-init.sh) vs overlay/upstream/
# (committed baseline). A mismatch means the scaffold generation moved, so the
# overlay copies below may be silently missing upstream changes.
PRISTINE_DIR="${BACKSTAGE_DIR}/.scaffold-pristine"
UPSTREAM_DIR="${OVERLAY_DIR}/upstream"
if [ -d "${PRISTINE_DIR}" ]; then
  drift=0
  while IFS= read -r -d '' f; do
    rel="${f#"${PRISTINE_DIR}"/}"
    if ! cmp -s "${f}" "${UPSTREAM_DIR}/${rel}"; then
      [ "${drift}" -eq 0 ] && echo "!! upstream drift, scaffold files no longer match platform/backstage/overlay/upstream/:" >&2
      echo "!!   ${rel}" >&2
      drift=1
    fi
  done < <(find "${PRISTINE_DIR}" -type f -print0)
  while IFS= read -r -d '' f; do
    rel="${f#"${UPSTREAM_DIR}"/}"
    if [ ! -f "${PRISTINE_DIR}/${rel}" ]; then
      [ "${drift}" -eq 0 ] && echo "!! upstream drift, scaffold files no longer match platform/backstage/overlay/upstream/:" >&2
      echo "!!   ${rel} (no longer generated by the scaffold)" >&2
      drift=1
    fi
  done < <(find "${UPSTREAM_DIR}" -type f -print0)
  if [ "${drift}" -eq 1 ]; then
    echo "!! Review what upstream changed:" >&2
    echo "!!   diff -ru platform/backstage/overlay/upstream local/backstage/.scaffold-pristine" >&2
    echo "!! Port those changes into overlay/files/, then refresh the baseline:" >&2
    echo "!!   make backstage-baseline" >&2
  fi
else
  echo "    (no .scaffold-pristine/ snapshot, drift check skipped; a fresh \`make backstage-init\` will create it)"
fi

# 1. Layer overlay files on top of the scaffolded tree.
echo "==> syncing overlay files from platform/backstage/overlay/files/"
( cd "${OVERLAY_DIR}/files" && find . -type f -print0 | \
  while IFS= read -r -d '' f; do
    target="${BACKSTAGE_DIR}/${f#./}"
    mkdir -p "$(dirname "${target}")"
    cp "${f}" "${target}"
  done )

# 2. Inject platform catalog and templates under examples/.
echo "==> syncing platform catalog from platform/backstage/catalog/"
rm -rf "${BACKSTAGE_DIR}/examples/catalog"
mkdir -p "${BACKSTAGE_DIR}/examples/catalog"
cp -R "${PLATFORM_CATALOG_DIR}/." "${BACKSTAGE_DIR}/examples/catalog/"

echo "==> syncing platform templates from platform/backstage/templates/"
rm -rf "${BACKSTAGE_DIR}/examples/templates"
mkdir -p "${BACKSTAGE_DIR}/examples/templates"
cp -R "${PLATFORM_TEMPLATES_DIR}/." "${BACKSTAGE_DIR}/examples/templates/"

# Render ${FORGEPATH_*} placeholders in each scaffolder template.yaml so the
# synced copy carries the fork's owner/repo/branch. forgepath_render matches only
# single-brace `${VAR}`, leaving Nunjucks `${{ ... }}` untouched.
echo "==> rendering FORGEPATH_* placeholders in scaffolder templates"
echo "    OWNER=${FORGEPATH_GITHUB_OWNER}  REPO=${FORGEPATH_GITHUB_REPO}  BRANCH=${FORGEPATH_TARGET_BRANCH}"
find "${BACKSTAGE_DIR}/examples/templates" -type f -name template.yaml | \
  while IFS= read -r f; do
    tmp="$(mktemp)"
    forgepath_render "${f}" > "${tmp}"
    mv "${tmp}" "${f}"
  done

# 3. Inject the TechDocs source tree (mkdocs.yml + docs/*.md). Referenced by the
# forgepath-platform Component via `backstage.io/techdocs-ref: dir:../docs`.
echo "==> syncing platform docs from platform/docs/"
rm -rf "${BACKSTAGE_DIR}/examples/docs"
mkdir -p "${BACKSTAGE_DIR}/examples/docs"
cp -R "${PLATFORM_DOCS_DIR}/." "${BACKSTAGE_DIR}/examples/docs/"

echo "==> sync complete"
