apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  # namespace omitted on purpose, see deployment.yaml.
  labels:
    app: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: {% if values.exposeOnLocalhost %}NodePort{% else %}ClusterIP{% endif %}
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: ${{ values.port }}
      {%- if values.exposeOnLocalhost %}
      nodePort: 30080
      {%- endif %}
